### PR TITLE
Push the next sched contribution date forward before talking to iATS

### PR DESCRIPTION
**Pull request by adixon**
to better handle partial server failures, e.g. timeouts, as per #268 and as reported in #264.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@adixon we've been thinking about this issue today - ie. we start a recurring & it fails & then it retries. WMF traditionally had a slightly odd way of handling this & I want to be more standardised & we were leaning towards something similar to this ie

1) we move the next sched date before the attempt
2) we make the attempt
3) if we record a failure we set the failure date
4) we have a separate job retrying failed ones according to failure date

Alternatives are that on failed we just reset the next sched date to the failure date but that feels intuitively wrong and that we have a special contribution status that means 'Being processed' and we don't retry unless that is reset - this is closer to the existing WMF method but I think we must have extra handling to keep it from becoming a blocker if there is a fail mid process.

My preference is that core apis should support payment processors to all use the same approach although a core api to support the above is not obvious to me.

Also ping @mattwire @mlutfy for any thoughts

**Comment by eileenmcnaughton** [comment]
AH now I've looked at it more I realise we have been encouraging people to do

- repeat transaction - with status of pending
- do payment
- call complete transaction

We could make it so that we push out the next_sched_recur date when we call repeattransaction - I just have to think through where that is used from / the implications....

**Comment by KarinG** [comment]
Please note that this issue is solved w/ Alan’s commits referenced above (it’s not closed yet b/c it’s not in an official release yet, but a few of our clients are using it in a pre-release).

**Comment by eileenmcnaughton** [comment]
Right - I picked the issue up as a place to discuss the generic issue - ie. not specific to IATS or WMF (who have a different solution in place at the moment). Ideally we would have a generic way of doing this sort of stuff that affects many (most?) processors

**Comment by eileenmcnaughton** [comment]
(but I'll probably create an issue *somewhere else* soon)

**Comment by mattwire** [comment]
@eileenmcnaughton Ping me once you've created the generic issue. We probably shouldn't force handling of next_sched_contribution_date in all cases but it would be really nice if it did something sensible by default, also a few related variables - cycle_day, failure retry date (which generally is next_sched.. but processor may override).

**Comment by adixon** [comment]
Yeah, handling failure is tricky and we're still learning as evidenced by this issue ...

Some shared core code to make this easier and more consistent across processors is a good theory, though I find each processor has some slightly different things so making the functions fairly low level is probably a useful approach.

For example - what to do about the recurring failure. We get some codes back from iATS that are sort-of-reliable that give us a reason why it failed. In a case of "stolen card" or other critical type failure, we're putting the recurring in pending right away to alert the administrator that action is needed and no more attempts should be made. But if we're not sure, then we try again with the next (regular) recurring scheduled job, so their recurring day will drift forward. This is making the assumption that the card failed due to a temporary issue that we don't need to worry about it.

I also document a way to allow a second attempt to keep to the original schedule (I call it "catchup mode"), which uses an argument to the recurring script (catchup=1) - that has the effect that if the payment does go through on a subsequent attempt it'll be back dated to the date it was supposed to go out.

Then, after at least three failures (configurable in the backend) without a success, the next scheduled date is pushed forward a month. Because those three failures are still identified in the recurring schedule record, a single failure will again push it forward a month, so the system is really just doing it's best with what it's got at that point.

There are some clients that have lots of donors that can be expected to do followup, but there are also those that for lots of reasons just end up on auto-pilot with no one looking at the money for a stretch (e.g. a single employee organization, when the ED changes). So I try to support both ends of the spectrum, and handle fairly complex situations of failure, both critical and temporary.

**Comment by eileenmcnaughton** [comment]
@adixon so you've put a lot of thought into it. I feel like you are saying ' the processor also knows whether it is a permanent failure or not & we handle  permanent failures differently' - I think we could come up with a generic protocol there. Is there anything else you can think of that is currently processor specific?

**Comment by adixon** [comment]
Yeah, I think we have five kinds of failures to consider for these server-managed recurring payment jobs.

1. Failure to execute - e.g. when the server runs out of memory in the middle of a transaction attempt.
2. Failure to communicate - when CiviCRM can't get an answer to the request - in the case of iATS, that's a SOAP timeout. That's what this issue is resolving.
3. A communicated server failure - e.g. iATS comes back and says "Unable to talk to the relevant visa/mastercard/whatever server".
4. A transitory card failure - one of a collection of return codes that imply the transaction failed but it might work in the future (e.g. card over limit, or unknown failure type thing).
5. A known serious card failure - i.e. something like "this card has been stolen".

The first two need to be handled implicitly in the code by pushing the next recurring date forward before anything else - otherwise the process may get interrupted with a payment actually happening but without civicrm being aware of it (and consequently repeating the payment request when it shouldn't), i.e. that's what this issue is about. In the case of iATS we have the nice feature that we can query the transaction log and catch up with what might have happened without us knowing about it.

3. 4. and 5. all need separate code logic to handle the setting of the next recurring date and potentially altering the status of the recurring schedule.

**Comment by eileenmcnaughton** [comment]
Thanks @adixon - that's helpful. In the case of 1 the script falls over. I had assumed that to be the case in 2 as well? Hence the failure to update dates ?

My instinct at the moment is that we through a paymentProcessorException at the moment when there is a failure & we should introduce some more variants of this exception

**Comment by eileenmcnaughton** [comment]
OK - issue in gitlab to carry on thinking about this https://lab.civicrm.org/dev/core/issues/905

**Pull request merged**
