### PR TITLE
Update Unit Test code to work with PHPUnit8 whilst maintaining suppor…

### PR DESCRIPTION
**Pull request by seamuslee001**
…t for current phpunit versions

ping @KarinG @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
nice!

**Comment by KarinG** [comment]
+6 −169 🎉

**Comment by seamuslee001** [comment]
@KarinG @adixon any update on this PR? Do you need anything from me?

**Comment by KarinG** [comment]
Sorry - had slipped off the radar.

**Pull request merged**
