### PR TITLE
BaseTestClass - Misc tweaks

### PR DESCRIPTION
**Pull request by totten**
While looking to setup CI for this extension, I was reading test classes. These are a few small tweaks. They're mostly aesthetic.

### CODE REVIEW

**Comment by KarinG** [comment]
Thank you Tim!

**Comment by KarinG** [comment]
Alan - can you please merge this?

**Comment by totten** [comment]
Aside: first test run with itaspayments on Jenkins. https://test.civicrm.org/job/CiviCRM-Core-Matrix/CIVIVER=4.7.24-rc,label=ubuntu1604/4068/

It shows the `BaseTestClass` warning, but otherwise seems to be working. :)

**Comment by KarinG** [comment]
Very cool! :-)

**Comment by KarinG** [comment]
So did it run the tests in ContributionIATSTest.php ?

**Comment by totten** [comment]
Yup. You have to drill down a little further to see the passing tests (eg "Test Result" => "All Tests; (root)"). There's a long a list of passing tests, but you can search for "iats". 

screen shot 2017-08-19 at 10 51 52 am

(Note: The bold lines indicate that it was the first time that the test was executed in the given configuration, `CIVIVER=4.7.24-rc,label=ubuntu1604`.)

**Comment by KarinG** [comment]
Awesome - thanks Tim! Looking fwd to adding more tests soon.

**Comment by adixon** [comment]
Yes, a year ago I added some code to escape data with which I was building xml, and used a PHP constant that was only added in 5.4.0. I've just added a workaround here https://github.com/iATSPayments/com.iatspayments.civicrm/commit/a653e7ac5a9f476d59175bf58da0a934c451404b so that it should work for 5.3 as well.

**Pull request merged**
