### PR TITLE
Run civix upgrade

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This applies the latest fixes/ updates from Civix to IATS

Per @larssandergreen this addresses at least one extension from https://github.com/civicrm/civicrm-core/pull/27565#issuecomment-1732091674 & is generally good practice to do this anyway

### CODE REVIEW

**Comment by adixon** [comment]
Thanks for this. I'm trying to dig backwards to figure out what problem this is trying to solve and what issues might arise as unintended side effects. It looks generally like improvements and getting rid of old deprecated stuff, but I see two potential flags:
1. php 7.x compatibility (is this patch still php7.x compatible?)
2. removal of the menu hook in the civix generated file (though I can't recall whether I'm using that or not).

In any case, I'm going to assume this is not something that I can pull blindly, that it would need some testing before going live, correct me if I'm wrong.

**Comment by eileenmcnaughton** [comment]
@adixon yeah - civix upgrades are backwards compatible - you can pretty much blndly upgrade civix on the regular - @totten will give you the long version if you want I'm sure

**Review by adixon — APPROVED** [review]
Eileen and Tim say it's cool, so it's cool.

**Comment by totten** [comment]
> (@eileenmcnaughton) totten will give you the long version if you want I'm sure

Well, the long version is a hyperlink. :smiley:

https://civicrm.org/blog/totten/civix-v2205-how-remove-million-lines-extra-code. 

> (@adixon) what issues might arise as unintended side effects

When one executes `civix upgrade`, it shows notes about possible side-effects. Eileen probably would've mentioned if any of them sounded alarming. Skimming the files here, the main thing that sticks out to me is:

```xml
 <compatibility>
    <ver>5.49</ver>
  </compatibility>
```

This is good -- because it means that several considerations are not applicable.

**Pull request merged**
