### PR TITLE
Update code formatting for half-dozen API files

### PR DESCRIPTION
**Pull request by totten**
According to https://docs.civicrm.org/dev/en/latest/extensions/lifecycle/#review-criteria, official extensions should follow the same code-formatting as core.

You can get a general report on code-style compliance by running:

```
cd com.iatspayments.civicrm
find -name '*php' | civilint -
``` 

I was a bit impatient and started this process as follows -- this command sets up an interactive review for all your PHP files. (The command will display issues for file `#1`; then you can edit in another window; then re-evaluate file `#1`; and eventually move on to file `#2`, file `#3`, etc.)

```
cd com.iatspayments.civicrm
eval $( find -name '*php' | xargs echo phpcs-civi -a )
```

The process is amenable to divide-and-conquer (e.g. different people tackling different files).

You can alternatively look into using an IDE or `phpcbf`/`phpcbf-civi` to reformat source-code. (Those tools are fast and fix most issues -- although they takes more setup and may have a few wonky edge-cases.) Still, it's good to do a couple files with `phpcs-civi -a` as a way to quickly learn the style guidelines.

### CODE REVIEW

**Comment by adixon** [comment]
Very nice, thanks for this. I'm tempted to just approve them all, a quick review didn't flag anything outrageous and I suspect any potential for introducing problems is going to be subtle and not visible til we run some tests. Any reason not to? Am I being too lazy?

**Comment by totten** [comment]
FWIW, I also re-read the diff and thought the changes looked OK.

For this kind of whitespace cleanup, I'd gauge the risk by patch size. A small patch for one file can get approved from eyeballing. But if your eyes start glazing over because the giant patch induces boredom or incomprehension, then look for some other validation (e.g. double-checking the cleanup methodology and/or running some kind of test). 

Personally, my eyes didn't glaze over when reading this patch, so it's probably OK.

Aside: On the chance that there is a mistake somewhere, I find it helpful to break the change into smaller chunks: each commit only touches one file, and the PR only has a couple commits/files, and you can do fix other files in other PRs.

**Comment by KarinG** [comment]
How about: once all the cleanup is completed/committed - I pull that onto semper-it.com and along with the latest RC and run a fresh manual test-matrix? That should give us some confidence in both.

**Comment by lynxlynxlynx** [comment]
You can append ?w=1 to the view and it will skip whitespace changes:
https://github.com/iATSPayments/com.iatspayments.civicrm/pull/230/files?w=1

**Comment by adixon** [comment]
I've just run an eyeball review and I think it's worth just pushing through. The automated tests should catch any syntax errors and really big bobos. Karin - hold off on the manual test-matrix til we do a bit more of the outstanding little bug-fixes (e.g. the re-verification issue).

**Comment by KarinG** [comment]
Right... I started working on that - but got distracted;

**Comment by KarinG** [comment]
PS - Thank you @totten!

**Pull request merged**
