### PR TITLE
Handle doPayment requests of $0 amounts without a transaction attempt.

### PR DESCRIPTION
**Pull request by adixon**
Replaces https://github.com/iATSPayments/com.iatspayments.civicrm/pull/363

### CODE REVIEW

**Comment by mattwire** [comment]
@adixon Looks fine to me!

**Comment by yurg** [comment]
@adixon Is this in the "core" iATS yet please? Have got this issue while moving out from the iATS "3rd party" extension to iATS core extension  in 5.56.2.

**Comment by adixon** [comment]
It's in the upcoming 1.7.5 version. There's only one extension - it's distributed with core sometimes, but it's a third party.

**Comment by yurg** [comment]
@adixon There were two of them and we removed the one from `public_html/wp-content/uploads/civicrm/ext`, so only located in `public_html/wp-content/plugins/civicrm/civicrm/ext` is left and activated.

**Comment by adixon** [comment]
Yes, you may have more than one copy installed on your system, but there's only one "version". iATS was distributed with CIviCRM core in the downloadable tar/zip files, but I don't think it is any longer. Even then, it was just being pulled from this same repo. A very, very long time ago, there was also a different repo here: https://github.com/adixon/ca.civicrm.iats

**Comment by yurg** [comment]
Right, thank you. Have replaced  1.7.4 by 1.7.5-rc2, will see how it goes.

**Pull request merged**
